### ISSUE TITLE
Keretrendszer kiiratáshoz, bekéréshez

### ISSUE THREAD

**Issue by AbosaSzakal** [torpeBoiGo/aszteroidabanyaszat#12]

**Comment by AbosaSzakal** [comment]
Inicializálásnál nem tudok időben a nevet megadni a dolgoknak
A kilépést nem tudom hogy kéne a kérdéseknél

**Comment by woranhun** [comment]
kilépés: dobunk egy exceptiont. amit majd elkapunk a controllerben
